// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaqW3Hs1xJ6tw5r-XqkcGx7AeKuDKvevo',
    appId: '1:721498766471:web:64d1ec2047028f572f8c22',
    messagingSenderId: '721498766471',
    projectId: 'studentapp-f85ab',
    authDomain: 'studentapp-f85ab.firebaseapp.com',
    databaseURL: 'https://studentapp-f85ab-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'studentapp-f85ab.firebasestorage.app',
    measurementId: 'G-ERSM3CF4BK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1DJFRyW9uWC7lm3BIbPwc8fuQKam4E-c',
    appId: '1:721498766471:android:620cfc200c8ba8a22f8c22',
    messagingSenderId: '721498766471',
    projectId: 'studentapp-f85ab',
    databaseURL: 'https://studentapp-f85ab-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'studentapp-f85ab.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaqW3Hs1xJ6tw5r-XqkcGx7AeKuDKvevo',
    appId: '1:721498766471:web:64d1ec2047028f572f8c22',
    messagingSenderId: '721498766471',
    projectId: 'studentapp-f85ab',
    authDomain: 'studentapp-f85ab.firebaseapp.com',
    databaseURL: 'https://studentapp-f85ab-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'studentapp-f85ab.firebasestorage.app',
    measurementId: 'G-ERSM3CF4BK',
  );
}
